### ISSUE TITLE
Linux Kernel / Wireguard integration tasks

### ISSUE THREAD

**Issue by beurdouche** [project-everest/hacl-star#103]
**(LAST UPDATED on Dec 6th 9am GMT+1) by BB.**
with Jason @zx2c4

**General (required)**
- [x] No recursive function in the Kernel

**Coding style (required)**

- [ ] Tabs instead of spaces
- [x] Naming of the integers should be `u32` instead of `uint32_t` (Kernel)
- [ ] Brackets at the end of loops and branches should be at the end
- [x] Get rid of the prefix and suffix underscores
- [x] `inline static` should be `static inline`
- [ ] Trivial loop counters should be `int` instead of `uint32`
- [ ] Don't break lines for the return types and arguments of functions
- [x] Functions should be named with lowercase 
- [x] Functions should  have no module name prefix (Kernel)
- [x] Remove all `KRML_CHECK_SIZE`
- [x] Remove all empty scopes
- [x] `i = i + 1` should always be `++i` in loops
- [x] `sizeof` should be treated as a function : `sizeof(*b) * 5` 
- [ ] `5  * sizeof(*input)` instead of `(u32)5U * sizeof (input + (u32)5U)[0U])`
- [x] Assuming native support for `UInt128` -> Replace `shift_left` by `<<` 

**Improvements**
- [x] Generate `const` keywords from kremlin
- [ ] Line break between declarations and functions
- [ ] Remove all unnecessary scopes
- [ ] Removing all the integer `U` suffixes when non necessary (array indices)

**Comment by msprotz** [comment]
For all the pretty-printing fixes, why don't you write a .clang-format file and use clang-format? This would give you much better control about breaking rules, etc. rather than turning kremlin into a formatter with a lot of option.

A quick google search yields https://gist.github.com/qlyoung/242ba15238ba417cb7721c45a3201497 for instance.

**Comment by zx2c4** [comment]
> For all the pretty-printing fixes, why don't you write a .clang-format file and use clang-format?

That won't cover _all_ the pretty-printing fixes, and of course clang-format isn't verified itself. But sure, I'm likely to do something similar in any case by hand.

------------

One thing we overlooked yesterday is that the current -donna implementation makes calls to `memzero_explicit` at the end, in order to burn all the sensitive intermediate data off the stack. This is a pretty desirable quality of a DH function, since without it there isn't forward secrecy.

**Comment by prosecco** [comment]
> One thing we overlooked yesterday is that the current -donna implementation makes calls to memzero_explicit at the end, in order to burn all the sensitive intermediate data off the stack. This is a pretty desirable quality of a DH function, since without it there isn't forward secrecy
> 
> 
I guess you did this by hand? Because agl’s donna doesn’t seem to do this.

-K.

**Comment by msprotz** [comment]
> That won't cover all the pretty-printing fixes
Interesting. Do you know which parts aren't covered? I just assumed that clang-format would take care of line breaks, spaces vs tabs, wrapping of function arguments, empty scopes, etc. I'm using it to reformat kremlib upon checkins and I've found it to cover a lot of my needs.

Thanks,

Jonathan

**Comment by zx2c4** [comment]
> I guess you did this by hand? Because agl’s donna doesn’t seem to do this.

Right. It looks something like this:

```c
static bool curve25519_donna(u8 mypublic[CURVE25519_POINT_SIZE], const u8 secret[CURVE25519_POINT_SIZE], const u8 basepoint[CURVE25519_POINT_SIZE])
{
	limb bp[5], x[5], z[5], zmone[5];
	u8 e[32];

	memcpy(e, secret, 32);
	normalize_secret(e);

	fexpand(bp, basepoint);
	cmult(x, z, e, bp);
	crecip(zmone, z);
	fmul(z, x, zmone);
	fcontract(mypublic, z);

	memzero_explicit(e, sizeof(e));
	memzero_explicit(bp, sizeof(bp));
	memzero_explicit(x, sizeof(x));
	memzero_explicit(z, sizeof(z));
	memzero_explicit(zmone, sizeof(zmone));

	return true;
}
```

**Comment by zx2c4** [comment]
Another item to add to the list:

* Replace loops that zero with `= { 0 }` in the declaration.

**Comment by zx2c4** [comment]
A version of hacl-star's curve25519 now ships inside of WireGuard: https://git.zx2c4.com/WireGuard/tree/src/crypto/curve25519-hacl64.h

It might be helpful to refer to this file for style.
