### ISSUE TITLE
Bringing _dev and fstar-master closer

### ISSUE THREAD

**Issue by msprotz** [project-everest/hacl-star#178]
Hello,

This is an issue to discuss a series of steps that can lead, in the end, to a successful merge of _dev into fstar-master. It's a long road, so this issue will attempt to break things down into sub-tasks that can be clearly assigned to a few people and that can be discussed individually.

There are numerous benefits to a merge. Personally, my goal is to minimize the amount of duplicated efforts; bring more synchronization between the two branches, to make it easier to flow fixes from fstar-master to _dev; and generally improve the experience enough that everyone is productive and comfortable with the tools, including CI.

This is only a draft, and I would love to have feedback from @beurdouche @polubelova @karthikbhargavan @R1kM @Frosne @s-zanella on what their pain points are and what they see as urgent or missing steps in the list below.

Here's a list of high-level tasks; I'm happy to provide detailed sub-lists for each item if anyone needs a more precise roadmap.

### Phase 1: make sure the overlapping parts of fstar-master and _dev are identical

- [x] lib: merge the latest version from _dev into fstar-master (Aymeric)
- [ ] specs: clean up hashes, hmac, hkdf (Karthik, Jonathan)
- [ ] code/hash: clean up specs and proofs; refresh sha3 and add blake2 (Karthik, Aymeric?)
- [ ] code/hmac: flow from _dev to fstar-master (Jonathan, Karthik)
- [ ] code/hkdf: higher-order and shared hkdf (Jonathan, Karthik)
- [ ] code/ed25519: wip (Aymeric, Marina)
- [ ] code/chacha20, poly1305: flow from _dev to fstar-master (Aymeric, Marina)
- [ ] specs/test: reuse Victor/Jonathan’s testing framework (Victor, Jonathan)
- [ ] Makefiles: individual makefiles for specs, lib, code/* (Jonathan, Marina, Aymeric, Santiago?)

At this stage, we should be able to merge fstar-master into _dev, meaning that any bugfixes following an upstream change in F* can be trivially reused by _dev. This also means that any changes that are considered for shared (common) parts between _dev and fstar-master can be tried out on fstar-master to ensure that they don't break CI and gain more confidence in the changes.

### Phase 2: prepare a merge from _dev into fstar-master

- [ ] lib: do a concerted effort for Lib.Random that leverages Vale and works for EverCrypt as well (Santiago, Marina, Karthik, Benjamin)
- [ ] lib: clean up Lib.ByteSequence.Tuples. Remove unnecessary libs and prove all admits (Santiago, Marina, Karthik, Benjamin)
- [ ] code/blake2: commit incremental version (Benjamin)
- [ ] stabilize, review and remove all admits in code/ (Karthik, Jonathan)

### Things that can progress in parallel, in experimental; to be merged at any time after that

- lib/Lib.IntVector: wip (karthik, marina)
- code/gf128: wip (marina)
- code/aes, code/aes-gcm: wip (karthik)
- code/p256: wip (natalia)
- code/kyber: wip (guillaume)

Please let me know how this sounds... I'll send out an email shortly to set up a meeting and talk about this over Skype.

Thanks,

Jonathan

**Comment by karthikbhargavan** [comment]
_dev is no longer active.
